// about/src/components/skeleton-shimmer/skeleton-shimmer.component.ts
import { Component, Input, ViewEncapsulation } from "@angular/core";

import "@shared/components/SkeletonShimmer/SkeletonShimmer.css";

@Component({
  selector: "app-skeleton-shimmer",
  standalone: true,
  encapsulation: ViewEncapsulation.None,
  templateUrl: "./skeleton-shimmer.component.html",
})
class SkeletonShimmerComponent {
  @Input() rounded = false;
  @Input() loadingClass?: string;

  get classes(): string {
    return ["skeleton-shimmer", this.rounded && "skeleton-shimmer--rounded", this.loadingClass]
      .filter(Boolean)
      .join(" ");
  }
}

export default SkeletonShimmerComponent;

// shared/src/components/SkeletonShimmer/SkeletonShimmer.tsx
import type { JSX } from "react";
import type { SkeletonShimmerProps } from "@shared/types/props";

import "@shared/components/SkeletonShimmer/SkeletonShimmer.css";

const SkeletonShimmer = ({ rounded, className }: SkeletonShimmerProps): JSX.Element => {
  const classes = ["skeleton-shimmer", rounded && "skeleton-shimmer--rounded", className]
    .filter(Boolean)
    .join(" ");

  return <div className={classes}></div>;
};

export default SkeletonShimmer;
