// users/src/components/SharedMfe/SharedMfe.vue
<script setup lang="ts" generic="P extends Record<string, unknown>">
import { ref, computed, onMounted, onBeforeUnmount, inject } from "vue";

import type { MfeCallbacks } from "shared/sdk";
import type { SharedMfeProps } from "@users/types/props";

const props = defineProps<SharedMfeProps<P>>();

const containerRef = ref<HTMLDivElement | null>(null);
const callbacks = inject<MfeCallbacks>("mfeCallbacks");

// Host div follows the `<className>-wrapper` convention: it derives its class from the
// mounted component's `className` so consumers don't need a manual wrapper element.
// Pass `wrapperClass` to override the inferred name.
const wrapperClass = computed<string | undefined>(() => {
  if (props.wrapperClass) return props.wrapperClass;
  const className = (props.componentProps as { className?: unknown }).className;
  return typeof className === "string" && className ? `${className}-wrapper` : undefined;
});

onMounted(() => {
  const el = containerRef.value;
  if (!el) return;

  props.module.mount(el, props.componentProps, callbacks ? { callbacks } : undefined);
});

onBeforeUnmount(() => {
  const el = containerRef.value;
  if (!el) return;

  props.module.unmount(el);
});
</script>

<template>
  <div ref="containerRef" :class="wrapperClass" />
</template>

// product/src/components/SharedMfe/SharedMfe.tsx
import { useRef, useEffect } from "react";
import { useInheritedContext } from "shared/sdk";

import type { JSX } from "react";
import type { SharedMfeProps } from "@product/types/props";

import "@product/components/SharedMfe/SharedMfe.css";

const SharedMfe = <P,>({
  module,
  componentProps,
  wrapperClass,
}: SharedMfeProps<P>): JSX.Element => {
  const containerRef = useRef<HTMLDivElement>(null);
  const inherited = useInheritedContext();
  const propsRef = useRef(componentProps);
  propsRef.current = componentProps;

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const options = inherited ? { callbacks: inherited.callbacks } : undefined;
    module.mount(container, propsRef.current, options);

    return (): void => {
      module.unmount(container);
    };
  }, [module, inherited]);

  // The host div owns the `<className>-wrapper` convention: it derives its class from the
  // mounted component's `className` so consumers don't need a manual wrapper element.
  // Pass `wrapperClass` to override the inferred name.
  const rawClassName = (componentProps as unknown as { className?: unknown }).className;
  const inferredWrapperClass =
    typeof rawClassName === "string" && rawClassName ? `${rawClassName}-wrapper` : undefined;
  const resolvedWrapperClass = wrapperClass ?? inferredWrapperClass;

  return (
    <div
      ref={containerRef}
      className={[resolvedWrapperClass, "shared-mfe__container"].filter(Boolean).join(" ")}
    />
  );
};

export default SharedMfe;
